kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./Dockerfile
  context: hugging-face-accelerate 

spec:
  operator: pytorch
  image: image
  command: "torchrun --nproc_per_node 1 main.py --mixed_precision bf16 --batch_size 105 --num_epochs 200" # --num_processes=={Number of GPUs}

  tensorboard:
    enabled: true 

  types:
    Master:
      count: 1
      resources:
        cpus: 16
        ramRatio: 2
        extraTolerations:
          - effect: NoSchedule
            key: node.kubernetes.io/unschedulable
            operator: Exists 
        rdma: # new
         # list of network devices to mount on the container
         devices: ["sriov_a", "sriov_b", "sriov_c", "sriov_d"]
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-H100-80GB-HBM3
    Worker:
      count: 1
      resources:
        cpus: 16
        ramRatio: 1
        extraTolerations:
          - effect: NoSchedule
            key: node.kubernetes.io/unschedulable
            operator: Exists
        rdma: # new
         # list of network devices to mount on the container
         devices: ["sriov_a", "sriov_b", "sriov_c", "sriov_d"]
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-H100-80GB-HBM3

