kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./Dockerfile
  context: hugging-face-accelerate 

spec:
  operator: pytorch
  image: image
  command: "torchrun --nproc_per_node 1 main.py --mixed_precision bf16 --batch_size=48 --num_epochs 200" # --num_processes=={Number of GPUs}

  tensorboard:
    enabled: true 

  types:
    Master:
      count: 1
      resources:
        cpus: 16
        ramRatio: 2
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-H100-80GB-HBM3-MIG-3g.40gb
    Worker:
      count: 1
      resources:
        cpus: 16
        ramRatio: 1
        accelerators:
          gpu:
            count: 1
            type: gpu
            product: NVIDIA-H100-80GB-HBM3-MIG-3g.40gb

